SRC := driver/driverExceptions.cpp
LIB := implementation/Exceptions.cpp
OUTPUT:= ../../../bin/exceptions

all: compile run
compile:
	@echo "Compiling gamestate driver"
	g++ $(SRC) $(LIB) -o $(OUTPUT)
run:
	$(OUTPUT)